### PR TITLE
Rokas api define access wip

### PR DESCRIPTION
**Pull request by RokasMarcinkevicius**
Commit to last project
image

### CODE REVIEW

**Comment by DaliusGrigolius** [comment]
sure

**Comment by TitasRink** [comment]
Truksta tvarkos

**Comment by RokasMarcinkevicius** [comment]
1 message
> Truksta tvarkos
Viskas cia ok

**Comment by RokasMarcinkevicius** [comment]
https://github.com/RokasMarcinkevicius/Branching/pull/1#issuecomment-1155586165
+1

**Comment by TitasRink** [comment]
bet funkcionalumo tikrai truksta :)

**Pull request merged**
